package com.ethem00.idogmod.entity.client.render.entity.animation;

import com.ethem00.idogmod.iDogMod;
import net.minecraft.util.Identifier;

public interface iDogEyeVariants {

    /**
     * WARNING! Some of these can be quite long... The scrollbar at the bottom may be a good friend to rely on!
     */
    public Identifier[] music_disc_default_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/default/idog_eyes_default.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/default/idog_eyes_default_inverted.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/default/idog_eyes_default_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/default/idog_eyes_default_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/default/idog_eyes_default_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/default/idog_eyes_default_4.png")};

    public Identifier[] music_disc_5_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_5.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/5/music_disc_5_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/5/music_disc_5_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/5/music_disc_5_3.png")};

    public Identifier[] music_disc_11_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_11.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/11/music_disc_11_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/11/music_disc_11_1.png")};

    public Identifier[] music_disc_13_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_13.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/13/music_disc_13_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/13/music_disc_13_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/13/music_disc_13_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/13/music_disc_13_3.png")};

    public Identifier[] music_disc_blocks_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_blocks.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blocks/music_disc_blocks_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blocks/music_disc_blocks_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blocks/music_disc_blocks_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blocks/music_disc_blocks_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blocks/music_disc_blocks_3.png")};

    public Identifier[] music_disc_cat_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_cat.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_4.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_5.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_6.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/cat/music_disc_cat_7.png")};

    public Identifier[] music_disc_chirp_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_chirp.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/chirp/music_disc_chirp_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/chirp/music_disc_chirp_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/chirp/music_disc_chirp_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/chirp/music_disc_chirp_3.png")};

    public Identifier[] music_disc_far_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_far.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/far/music_disc_far_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/far/music_disc_far_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/far/music_disc_far_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/far/music_disc_far_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/far/music_disc_far_4.png")};

    public Identifier[] music_disc_mall_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_mall.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mall/music_disc_mall_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mall/music_disc_mall_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mall/music_disc_mall_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mall/music_disc_mall_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mall/music_disc_mall_4.png")};

    public Identifier[] music_disc_mellohi_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_mellohi.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mellohi/music_disc_mellohi_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mellohi/music_disc_mellohi_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mellohi/music_disc_mellohi_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/mellohi/music_disc_mellohi_3.png")};

    public Identifier[] music_disc_otherside_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_otherside.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/otherside/music_disc_otherside_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/otherside/music_disc_otherside_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/otherside/music_disc_otherside_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/otherside/music_disc_otherside_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/otherside/music_disc_otherside_3.png")};

    public Identifier[] music_disc_pigstep_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_pigstep.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_4.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_5.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_6.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_7.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_8.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_9.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_10.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/pigstep/idog_eyes_pigstep_11.png")};

    public Identifier[] music_disc_relic_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_relic.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/relic/music_disc_relic_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/relic/music_disc_relic_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/relic/music_disc_relic_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/relic/music_disc_relic_3.png")};

    public Identifier[] music_disc_stal_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_stal.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/stal/music_disc_stal_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/stal/music_disc_stal_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/stal/music_disc_stal_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/stal/music_disc_stal_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/stal/music_disc_stal_4.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/stal/music_disc_stal_5.png")};

    public Identifier[] music_disc_strad_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_strad.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/strad/music_disc_strad_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/strad/music_disc_strad_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/strad/music_disc_strad_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/strad/music_disc_strad_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/strad/music_disc_strad_4.png")};

    public Identifier[] music_disc_wait_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_wait.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/wait/music_disc_wait_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/wait/music_disc_wait_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/wait/music_disc_wait_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/wait/music_disc_wait_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/wait/music_disc_wait_4.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/wait/music_disc_wait_5.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/wait/music_disc_wait_6.png")};

    public Identifier[] music_disc_ward_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/idog_eyes_ward.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/ward/music_disc_ward_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/ward/music_disc_ward_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/ward/music_disc_ward_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/ward/music_disc_ward_3.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/ward/music_disc_ward_4.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/ward/music_disc_ward_5.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/ward/music_disc_ward_6.png")};

    //For modded songs.
    //For the future, maybe check first letter from music_disc_[???]. To determine which variant you get.
    public Identifier[] music_disc_randomRed_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/red/music_disc_red_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/red/music_disc_red_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/red/music_disc_red_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/red/music_disc_red_3"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/red/music_disc_red_4.png")};

    public Identifier[] music_disc_randomGreen_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/green/music_disc_green_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/green/music_disc_green_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/green/music_disc_green_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/green/music_disc_green_3"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/green/music_disc_green_4.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/green/music_disc_green_5.png")};

    public Identifier[] music_disc_randomBlue_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blue/music_disc_blue_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blue/music_disc_blue_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blue/music_disc_blue_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blue/music_disc_blue_3"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/blue/music_disc_blue_4.png")};

    public Identifier[] music_disc_randomRainbow_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/rainbow/music_disc_rainbow_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/rainbow/music_disc_rainbow_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/rainbow/music_disc_rainbow_2.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/rainbow/music_disc_rainbow_3"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/rainbow/.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/rainbow/music_disc_rainbow_5.png")};

    public Identifier[] music_disc_randomCreeper_variants = {new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/creeper/music_disc_creeper_0.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/creeper/music_disc_creeper_1.png"), new Identifier(iDogMod.MOD_ID, "textures/entity/idog/eyes/variants/creeper/music_disc_creeper_2.png")};



    default boolean compareInteger(int first, int second) {
        return first > second;
    }
}
